services:

  # Criação API Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: ${DEBUG}
      MDB_HOST: ${MDB_HOST}
      MDB_PORT: ${MDB_PORT}
      MDB_USER: ${MDB_USER}
      MDB_PASS: ${MDB_PASS}
      MDB_NAME: ${MDB_NAME}
    networks:
      - app-net
    depends_on:
      - mongo

  # Mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MDB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MDB_PASS}
    networks:
      - app-net

  # Mongo Gui
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: ${MDB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MDB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MDB_PASS}
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongo
    networks:
      - app-net

  spark-master:
    hostname: spark-master
    container_name: spark-master
    image: wlcamargo/spark-master
    command: >
      /bin/sh -c "/usr/local/spark/sbin/start-master.sh & start-notebook.sh --NotebookApp.token=''"
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_DESTINY_KEY: ${AWS_DESTINY}
      MDB_HOST: ${MDB_HOST}
      MDB_PORT: ${MDB_PORT}
      MDB_USER: ${MDB_USER}
      MDB_PASS: ${MDB_PASS}
      MDB_NAME: ${MDB_NAME}
      PYTHONPATH: /home/user/project:/home/user/project/src:/home/user/project/src/spark
    env_file:
      - .env   
    volumes:
      - ./conf/util:/util
      - ./conf/env:/env
      - ./:/home/user/project
      - ./src/spark/spark-apps:/home/user/work
    ports:
      - 8889:8888 # Jupyter
      - 8083:8080 # Spark UI
      - 8040:4040 # Spark UI Jobs
      - 7077:7077 # Default port for communication
    networks:
      - app-net

networks: 
  app-net: 
    driver: bridge