# Generated by Django 5.1.3 on 2024-11-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
                ('quantidade_litros', models.FloatField()),
                ('total_categoria', models.FloatField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paises', models.CharField(max_length=50)),
                ('quantidade_kgs', models.FloatField()),
                ('valor', models.FloatField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paises', models.CharField(max_length=50)),
                ('quantidade_kgs', models.FloatField()),
                ('valor', models.FloatField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('cultivar', models.CharField(max_length=50)),
                ('quantidade_kgs', models.FloatField()),
                ('total_categoria', models.FloatField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
                ('quantidade_litros', models.FloatField()),
                ('total_categoria', models.FloatField()),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
