# Generated by Django 5.1.3 on 2024-11-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embrapa', '0003_alter_processamento_cultivar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comercio',
            old_name='origem_dados',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='exportacao',
            old_name='origem_dados',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='importacao',
            old_name='origem_dados',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='processamento',
            old_name='origem_dados',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='producao',
            old_name='origem_dados',
            new_name='tipo',
        ),
    ]
