# Generated by Django 5.1.3 on 2024-11-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embrapa', '0004_rename_origem_dados_comercio_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='tipo',
        ),
    ]
